---
title: "workshop9-collab"
format: html
editor: visual
---

load libraries

```{r}
library(tidyverse) # for wrangling and plotting
library(lterdatasampler) # for data access
library(ggeffects) # for models
library(here) # for easy file pathing
```



reading in data
```{r}
data(pie_crab) #reading in plum island ecosystem crab data set from lterdatasampler package

```

exploratory visualization

```{r}
ggplot(aes(x=latitude, y=size), data = pie_crab) + # set up plot
  geom_point(color = "royalblue") + # scatterplot
  labs(x = "latitude", y = "Size (mm)")+
  theme_minimal()
```


writing a model
```{r}
crab_model <- lm(size~latitude, #formula: response~predictor
                 data = pie_crab) #data from lter data sampler
#look at diagnostics here
par(mfrow = c(2,2)) 
plot(crab_model) #plotting the diagnostics

```

interpret model

```{r}
summary(crab_model) # look at results
```
Slope: 0.49 +/- 0.034
Y intercept: -3.6 +/- 1.27

For every one unit increase in latitude, we expect to see an increase in crab size of 0.49 +/- 0.034 mm.

model statistics: F(1,390) = 208.5, p < 0.0001, alpha = 0.05, R^2^ = 0.35







